### PR TITLE
GHC Ops Proposal

### PR DESCRIPTION
**Pull request by davean**
[Rendered](https://github.com/davean/tech-proposals/blob/main/proposals/000-ghc-ops.md)

In accordance with [the proposal process](https://github.com/haskellfoundation/tech-proposals/blob/be6a8f8bbe4350cd81a13a80cf4f80577c763b81/proposals/PROPOSALS.md) and after circulation on [Discourse](https://discourse.haskell.org/t/pre-hftp-devops-proposal/3747/14), [reddit](https://www.reddit.com/r/haskell/comments/r382bn/prehftp_ghc_devop_proposal/), and [twitter](https://twitter.com/haskellfound/status/1464492635456897024); I submit this proposal to the HFTT.

### CODE REVIEW

**Comment by goldfirere** [comment]
Very excited to see this proposed!

In reading the Discourse thread (thanks @davean for guiding that to a conclusion), there seemed to be an underlying assumption: that hiring a contractor was a short-term solution. I don't think that is necessarily the case.

I see pluses and minuses to the contractor / hire debate. I will write some down:

Pros to hire:
* We have direct control over the hire, and can direct their training, etc., to conform directly to our needs.
* Lower overhead: the contracting org doesn't take a cut.
* Stability: it would seem more likely that the performer would continue in their job for some time. At a contractor, the performer might be reassigned against our wishes.

Pros to contractor:
* Easier to ramp up / ramp down the amount of the contract. For example, if we wanted a blitz of attention early on (say, for 3 months of intensive CI cleaning), we could arrange for that, followed by ongoing maintenance from one person.
* Easier to change skill sets if necessary: if we mis-assess what we'll need at first, we can work with the contracting org to find a different performer who matches our needs better.

The best of both worlds might be to start with a contractor, hone our needs through experience, and then hire once we understand our needs better. Or maybe we just leave this particular decision up to the ED: phrase the proposal to say we wish to have one full-time person paid by the HF -- but the precise nature of the business relationship between the HF and the performer is up to the ED.

The truth is that I don't really know what I'm talking about here, so take all this with a few grains of salt. My big incentive to post is that it seemed, in the Discourse thread, that folks were equating "contractor" with "temporary", and I don't think this equivalence always holds.

**Comment by Ericson2314** [comment]
That's a fair point. I've already been more divisive than I want to but I will say

> Or maybe we just leave this particular decision up to the ED: phrase the proposal to say we wish to have one full-time person paid by the HF -- but the precise nature of the business relationship between the HF and the performer is up to the ED.

Sounds like a good default to me. Unless there is a strong stakeholder preference, e.g. from @bgamari or someone else, I think being open-ended is preferable. Again I happily support this proposal either way, but I like the principle of only codifying the essential details, and leaving the rest to the discretion of the HF staff.

**Comment by tomjaguarpaw** [comment]
Thanks very much for writing this up @davean. It sounds like a great way for the HF to have a huge impact on the whole Haskell community. Hopefully, one benefit for the Haskell community would be that the first releases of major versions of GHC become much more thoroughly tested than they are currently.

Thanks to @rae for elaborating on the contractor vs employee issue. At this stage, I personally don't see the need to determine that the relationship should be one or the other. In fact, an employment relationship brings significant risks to the HF:

* Increasing an organisation's number of employees by 50% is always painful, regardless of the size of the organisation, and can come with significant operational overheads over a period of several months.

* Hopefully everything will go smoothly with the new hire, but if for any reason not then we would suffer some degree of reputational harm if we had to terminate that relationship. It may be legally straightforward to terminate such a relationship (I'm not sure) but it could reflect poorly on the HF regardless of how well the HF conducts itself in the matter.

* If an employee performs poorly enough to be a net drain of resources, but not poorly enough to warrant termination (especially given the risks of termination noted above), then the situation is much harder to resolve than that of a contractor in the same position.

Now, the boundary between employee and contractor is a bit fuzzy. In fact *anyone* hired outside the US may legally *have to* be a contractor. But the distinction I want to draw is between someone that the HF has the moral responsibility to continue the relationship with indefinitely ("employee") and someone it doesn't ("contractor").

N.B. that Ben Gamari is a contractor and I don't get the impression that his work on GHC is in any way worse than it would be if he were an HF employee.  I suggest we open ourselves to the possibility of a similar arrangement in the proposed ops role. 

On that note, I think it would provide additional weight to the proposal if @bgamari and Moritz could add a few words of comment on the current situation and how they envisage things improving with a dedicated ops team member to work with.

**Comment by gbaz** [comment]
I don't think that this proposal specifies the nature of the employment contract, just that this is expected to be an ongoing position, and expected to work a full week. I'm happy to leave the exact nature of the employment in the control of hf officers.

**Comment by davean** [comment]
Do we want to edit the wording in some particular way here, or leave it as a given its up to the HF to execute on this as they see fit?

**Comment by tomjaguarpaw** [comment]
The interpretation that came to mind when I read "Hire a dedicated devops person" and "Deliver one hired developer" was of an "employee" relationship of the nature I described above, i.e. someone to whom the HF has an ongoing moral responsibility. I didn't get the impression that one of the important aspects was "works a full week". Now, that interpretation may be particular to me; others might read it in a different way.

Would it fit what you envisage to express it as "We aim to enter into a long-term engagement with an individual who will work on GHC devops on a full-time basis"?

**Comment by davean** [comment]
Perhaps people find this cleared up now?

**Comment by bgamari** [comment]
For what it's worth, I agree that there isn't a strong reason why the person filling this role would need to be an employee. To the contrary it may be easier if they were a contractor.

As noted in the proposal, managing devops at the scale of GHC is no small task. We target around a dozen platforms, and have a correspondingly large pool of CI runners. Moreover, some of our CI infrastructure could certainly use improvement (e.g. FreeBSD). 

Beyond carrying out maintenance on the runners, it would be nice if the person filling the role would be able to do some amount of work on various pieces of infrastructure surrounding the compiler. For instance, systematically monitoring compiler and runtime performance is a long-standing goal and while progress has been made recently, we still have a longs ways to go. Furthermore, help in diagnosing and triaging flaky tests, improving packaging infrastructure (e.g. putting in place the infrastructure to notarize Darwin builds), and assistance in maintaining head.hackage are all projects which do not require compiler experience but do require consistent, sustained attention. Depending upon the candidate, some or all of these could be areas of contribution.

**Comment by chreekat** [comment]
I think this is great! As somebody fully submersed within the DevOps event horizon, I am certain that the person you hire will have no end of work to do. :) DevOps is a force multiplier that multiplies... itself.

I would suggest that one missing responsibility is "facilitate volunteer DevOps efforts", unless you explicitly want others to be responsible for that.

I also think it would be very cool to include release and deployment to the list of further responsibilities. As written, the proposal seems to be focused on the *testing* piece of the CI pipeline, but DevOps doesn't stop there. Imagine tackling something like the system described at https://github.com/haskell/core-libraries-committee/issues/12#issuecomment-983732316!

I do worry that someone without good project management skills will get bogged down by the sheer size of the problem space.

**Comment by gbaz** [comment]
By unanimous decision of the HFTT committee (meeting of 1 December) we're happy to merge this.

**Comment by emilypi** [comment]
Echoing what @gbaz mentioned - great work @davean! Now it's in @myShoggoth's hands :smile:

**Pull request merged**
