### PR TITLE
[META] Clarify RFCs

### PR DESCRIPTION
**Pull request by david-christiansen**
I think this clarification matches our consensus from today's meeting.

### CODE REVIEW

**Comment by gbaz** [comment]
I vote yes.

**Comment by LaurentRDC** [comment]
+1 from me as well

**Comment by silky** [comment]
👍🏻

**Comment by davean** [comment]
Aye

**Comment by Ericson2314** [comment]
+1

**Comment by david-christiansen** [comment]
I suppose for the sake of good order, I should also vote "aye" here :-) We now have a majority - thanks.

**Pull request merged**
